# Generated by Django 6.0.1 on 2026-01-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='precio_unitario',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='disponible',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
