# Generated by Django 6.0.1 on 2026-01-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
